# Disable Eureka server looking for its cluster
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level:
    org.springframework: WARN

management:
  context-path: /manage
#endpoints:
#  health:
#    id: healthcheck

security:
  basic:
    enabled: false
  user:
    name: user
    password: secret

server:
  port: 8761
